### ISSUE TITLE
How did you compile gromacs in colab?

### ISSUE THREAD

**Issue by avinashkarkada** [pb3lab/ibm3202#1]
May I please know the procedure to compile gromacs in colab?
Because I wanted to compile it in gradient or kaggle.
Thank you

**Comment by pb3lab** [comment]
There are instructions for compilation on lab00_software.

https://colab.research.google.com/github/pb3lab/ibm3202/blob/master/tutorials/lab00_software.ipynb

If you are running the tutorials that use GROMACS only on your Google account and Drive, then the compiled GROMACS will be installed on your Drive in the folder IBM3202/gromacs-2020. Then, you can load your Drive onto Google Colab and keep using your compiled GROMACS version from your Drive.

For our latest tutorials, the only difference that we did from what is described above is that, after compilation was done, we generated a compressed version of the compiled GROMACS that we uploaded onto GitHub, such that every time we need GROMACS on Colab, we just download the readily compiled version. This is useful if you now want students to work quickly on these tutorials without them having to compile GROMACS on their own (which already takes ~30 min on Colab).

Let me know if that helps.

**Comment by avinashkarkada** [comment]
Yea that's great!
I was trying to do the same on Gradient notebooks and wanted to know the procedure.
Thank you very much. This helps.
