### ISSUE TITLE
Colab Crashed during running the lab 6:

### ISSUE THREAD

**Issue by recervictory** [pb3lab/ibm3202#2]
This course error during run 
`!conda install -c conda-forge -c bioconda mgltools openbabel zlib --yes`

I think there is issue between python 2.7 and python 3 in colab notebook: I tried not unable to resolve: Showing following error 
```
/bin/bash: /usr/local/lib/libtinfo.so.5: no version information available (required by /bin/bash)
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
ImportError: No module named pip
```

**Comment by pb3lab** [comment]
For the first error (libtinfo.so.5), you have to install ncurses via conda
For the second error (pip), you have to install pip using condacolab. This is why we install everything that needs pip BEFORE installing condacolab in our notebooks.

!conda install -c conda-forge -c bioconda mgltools openbabel zlib ncurses pip --yes

Hope this helps
