### ISSUE TITLE
Collab can't run Gromacs

### ISSUE THREAD

**Issue by Muzetia** [pb3lab/ibm3202#3]
I have done a handful of **MD simulations** with this method that you have kindly provided for us, and I was doing the last one that this thing happened. And I don't know how to solve it. I really need this. **I'm doing my thesis with it,** It would be so great if you could help me. 
the error is: 
`gmx: error while loading shared libraries: libhwloc.so.5: cannot open shared object file: No such file or directory`
![Screenshot 2023-01-18 211213](https://user-images.githubusercontent.com/116648763/213255941-629f0620-2b79-48fb-8ab6-9e6d6a94f20e.png)

**Comment by Muzetia** [comment]
I installed the package like this an it worked, thank you guys.

```
!wget https://download.open-mpi.org/release/hwloc/v1.11/hwloc-1.11.13.tar.gz


!tar xzf hwloc-1.11.13.tar.gz
!cd /content/hwloc-1.11.13
! /content/hwloc-1.11.13/configure
!make
!sudo make install

```

**Comment by engelberger** [comment]
Thanks for reporting, I added a hwloc cell to notebook 07

https://github.com/pb3lab/ibm3202/commit/d1f3ddf3e223d16d1798d661dbb133fac639c0fc
