### ISSUE TITLE
Colab docking issue with file dependency written in python 2

### ISSUE THREAD

**Issue by ppxasjsm** [pb3lab/ibm3202#5]
I am trying to run tutorial 6 for docking and the script preapare_receptor4.py and preapre_ligand4.py both seem to be written in python 2.7 when I try and run it on colab. 

As a result, I get the following error:

```
#Parameterizing and adding Gasteiger charges into our protein using MGLtools!prepare_receptor4.py -r $singlepath/1hsg_prot.pdb -o $singlepath/1hsg_prot.pdbqt -A hydrogens -U nphs_lps -v

  File "/usr/local/bin/prepare_receptor4.py", line 22
    print "Usage: prepare_receptor4.py -r filename"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

Where does the prepare_receptor4.py come in? Any chance there exists a python 3.+ version?

**Comment by pb3lab** [comment]
We added some modifications. Should be fixed now!
